---
- hosts: all
  tasks:
    - name: install the latest version of nano
      shell: "ip a | grep ens224 | grep inet | awk '{ print $2 }'"
      register: ipa_result
    - debug: msg="{{ ipa_result.stdout }}"
